apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-secret
  namespace: data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mariadb-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: prod/mariadb
        property: MYSQL_ROOT_PASSWORD
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: prod/mariadb
        property: MYSQL_DATABASE
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ceph-csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ceph-csi-rbd-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        userID: TEAM1
        userKey: "{{ .userKey }}"
  data:
    - secretKey: userKey
      remoteRef:
        key: prod/ceph-rbd
        property: userKey
