apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kosa-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/KOSA-cloud-1/k8s-manifests'
    targetRevision: feature/mornitoring
    path: argocd/applications
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground  # 리소스 삭제 순서 보장
      - ApplyOutOfSyncOnly=true   # 변경된 리소스만 apply (속도 향상)
