apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1         # maxSurge: 업데이트 중 최대로 추가될 수 있는 파드 수
      maxUnavailable: 1   # maxUnavailable: 업데이트 중 사용 불가능할 수 있는 최대 파드 수
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: gateway
      containers:
      - name: gateway
        image: fhwang98/gateway:a0434e2db7f5ee9f272db7699337b749798484ab
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway  #수정 필요 frontend
  ports:
  - port: 5000
    targetPort: 5000
