apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-rbd-smoke-test
  namespace: data
  labels:
    app.kubernetes.io/name: ceph-rbd-smoke-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 1Gi
