apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    kubernetes.io/metadata.name: metallb-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    kubernetes.io/metadata.name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    kubernetes.io/metadata.name: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    kubernetes.io/metadata.name: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: backup
  labels:
    kubernetes.io/metadata.name: backup
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    kubernetes.io/metadata.name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: ceph-csi-rbd
  labels:
    kubernetes.io/metadata.name: ceph-csi-rbd
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    kubernetes.io/metadata.name: external-secrets
