apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kosa-namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  project: default
  source:
    repoURL: 'https://github.com/KOSA-cloud-1/k8s-manifests'
    targetRevision: feature/monitoring
    path: namespaces
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
