apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kosa-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: 'https://github.com/KOSA-cloud-1/k8s-manifests'
    targetRevision: dev
    path: external-secrets
    directory:
      recurse: true
      include: '*.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
