apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kosa-data
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/KOSA-cloud-1/k8s-manifests'
    targetRevision: dev
    path: galera
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
