apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kosa-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: 'https://github.com/KOSA-cloud-1/k8s-manifests'
    targetRevision: feature/monitoring
    path: infra
    directory:
      recurse: true
      exclude: 'metallb-config.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
