apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kosa-monitoring-local-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  source:
    repoURL: 'https://github.com/KOSA-cloud-1/k8s-manifests'
    targetRevision: feature/monitoring-manifest
    path: monitoring
    directory:
      include: 'local-storage.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
