apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: default
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: kube-prometheus-stack
      targetRevision: 85.2.0
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/monitoring/kube-prometheus-stack-values.yaml
          - $values/monitoring/kube-prometheus-stack-persistence-values.yaml
    - repoURL: 'https://github.com/KOSA-cloud-1/k8s-manifests'
      targetRevision: dev
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
