apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway
  namespace: apps
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-server
  namespace: apps
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: auth-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: employee-server
  namespace: apps
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: employee-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: photo-service
  namespace: apps
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: photo-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx
  namespace: apps
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nginx
