apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: auth-server
      containers:
      - name: auth-server
        image: kosa1team/auth-server:b3b4cc8458de68a155f3eb464b59e2e3b797b099
        ports:
        - containerPort: 5001
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
        env:
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: JWT_SECRET_KEY
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: ADMIN_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
spec:
  selector:
    app: auth-server
  ports:
  - port: 5001
    targetPort: 5001
